---
title: "Incubation TIN"
format: html
---

# Running Code


```{r Packages}
install.packages("reshape2")

library(tidyverse) # for data wrangling and plotting
library(car) # for Anova function
library(lme4)
library(broom) # for model residuals extraction
library(emmeans) # for model mean extraction
library(multcomp) # for pairwise comparison letter display
# install.packages("multcompView")
library(multcompView)
library(reshape2)
```

```{r data import}
nitrogen_raw <- read_csv("../incubationstudy_n/data/incubation_nitrogen_processed.csv")

nitrogen_raw
```

```{r summary}
summary(nitrogen_raw)
```

```{r transform trt/rep to factor}
nitrogen_df <- nitrogen_raw %>%
  mutate(rep = factor(rep),
         lem_field = factor(lem_field))

nitrogen_df
```

```{r wrangled}
summary(nitrogen_df)
```
# EDA Plots
```{r EDA nh3 boxplot}
#meltdf <- melt(nitrogen_df,id="expday")
ggplot(nitrogen_df,aes(x = expday,
                       y = nh3_mgkg_dry,
                       colour = lem_field, 
                       linetype = lem_add,
                       group = trtname
                  )) + 
  facet_grid(site~.) +
  geom_point() +
  geom_line() +
  theme_bw()


ggsave("../output/nh3_incubation_plot.png",
       height = 4,
       width = 6)

```

```{r EDA no3 boxplot}
#meltdf <- melt(nitrogen_df,id="expday")
ggplot(nitrogen_df,aes(x = expday,
                       y = no3_mgkg_dry,
                       colour = lem_field, 
                       linetype = lem_add,
                       group = trtname
                  )) + 
  facet_grid(site~.) +
  geom_point() +
  geom_line() +
  theme_bw()


ggsave("../output/no3_incubation_plot.png",
       height = 4,
       width = 6)
```

```{r EDA tin boxplot}
#meltdf <- melt(nitrogen_df,id="expday")
ggplot(nitrogen_df,aes(x = expday,
                       y = tin_mgkg_dry,
                       colour = lem_field, 
                       linetype = lem_add,
                       group = trtname
                  )) + 
  facet_grid(site~.) +
  geom_point() +
  geom_line() +
  theme_bw()


ggsave("../output/tin_incubation_plot.png",
       height = 4,
       width = 6)
```

# Nitrate Model

```{r NO3 model}
# Changing to sum-to-zero contrast
options(contrasts = c("contr.sum", "contr.poly"))
nitrogen_df

# Model fitting
nitro_mod <- lm(no3_mgkg_dry ~ rep + expday*lem_add*site*lem_field, 
               data = nitrogen_df)
nitro_mod

# Summary
summary(nitro_mod)
```
```{r ANOVA}
Anova(nitro_mod, type=3)
```
## NO3 Check Assumptions
```{r residuals}
no3_resid <- augment(nitro_mod) %>%
  mutate(.studresid=rstudent(nitro_mod))

no3_resid
```
###NO3 Resid Independence

```{r no3 resid independ}
ggplot(no3_resid, aes(x=.fitted, y=.studresid))+
  geom_hline(yintercept = 0, color="red")+
  geom_point(shape = 21,
             fill = "purple", 
             size = 3,
             alpha = .7)+
  #geom_smooth()+
  geom_hline(yintercept = c(-3,3), color = "red")+
  theme_bw()
```
### NO3 Residual homoscedasticity  
```{r no3 }
ggplot(no3_resid, aes(x=.fitted, y=.studresid))+
  geom_hline(yintercept = 0, color="red")+
  geom_point(shape = 21,
             fill = "purple", 
             size = 3,
             alpha = .7)+
  geom_smooth()+
  geom_hline(yintercept = c(-3,3), color = "red")+
  theme_bw()
```
### NO3 Resid Normality 
```{r no3 qq plot}
ggplot(no3_resid, aes(sample=.studresid))+
  stat_qq(  shape = 21,
            fill = "purple", 
            size = 3,
            alpha = .7
  )+
  stat_qq_line()+
  labs(x = "Theoretical quantile",
       y = "Sample quantile")+
  theme_bw()
```
```{r residual bell curve}
ggplot(no3_resid, aes(x=.studresid))+
  geom_density(color = "black",
               fill = "purple",
               alpha = .7)+
  scale_x_continuous(breaks = c(-3,0,3), limits = c(-3,3))+
  theme_bw()

```

### NO3 Outliars
```{r}
ggplot(no3_resid, aes(x=.fitted, y=.studresid))+
  geom_hline(yintercept = 0, color="red")+
  geom_point(shape = 21,
             fill = "purple", 
             size = 3,
             alpha = .7)+
  geom_smooth()+
  geom_hline(yintercept = c(-3,3), color = "red")+
  theme_bw()

```
## NO3 Means and Pairwise Comparisons
```{r no3 interaction means all}
no3_means_all <- emmeans(nitro_mod,
                          ~lem_add:site:lem_field)

no3_means_all
```
```{r no3 interaction pwc all}
no3_cld_all <- cld(no3_means_all, 
                   reversed=T, 
                   adjust="none",
               Letters=letters,
               alpha = 0.05)

no3_cld_all
```
```{r no3 selected pwc}
no3_cld_selected <- no3_cld_all %>%
  as.data.frame() %>%
  mutate(letter = trimws(.group)) %>% 
  mutate(trtname = paste0(site, "+", lem_field, "+", lem_add))
  

no3_cld_selected
```

```{r rcbd final plot}
ggplot() +
  geom_boxplot(data = nitrogen_df,
               aes(x = trtname,
                   y = no3_mgkg_dry,
                   fill = trtname,
                   #color = nrate_kgha,
                   )
               ) +
geom_jitter(data = nitrogen_df,
            aes(x = trtname,
                y = no3_mgkg_dry,
                color = trtname),
            alpha = 0.6) +
  geom_label(data = no3_cld_selected,
            aes(x = trtname,
                y = emmean,
                label = letter),
            size = 3,
            label.padding = unit(.1, "lines")) +
  labs(x = "N Rate + K Rate",
       y = "Nitrate") +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  theme(legend.position = "none")
  


```

# Ammonia Model

```{r NH3 model}
# Changing to sum-to-zero contrast
options(contrasts = c("contr.sum", "contr.poly"))
nitrogen_df

# Model fitting
nh3_mod <- lm(nh3_mgkg_dry ~ rep + expday*lem_add*site*lem_field, 
               data = nitrogen_df)
nh3_mod

# Summary
summary(nh3_mod)
```
```{r NH3 ANOVA}
Anova(nh3_mod, type=3)
```

# TIN Model

```{r TIN model}
# Changing to sum-to-zero contrast
options(contrasts = c("contr.sum", "contr.poly"))
nitrogen_df

# Model fitting
tin_mod <- lm(tin_mgkg_dry ~ rep + expday*lem_add*site*lem_field, 
               data = nitrogen_df)
tin_mod

# Summary
summary(tin_mod)
```
```{r TIN ANOVA}
Anova(tin_mod, type=3)
```



